apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-ashiato
  namespace: pod-ashiato
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-ashiato-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-ashiato
subjects:
- kind: ServiceAccount
  name: pod-ashiato
  namespace: pod-ashiato
roleRef:
  kind: ClusterRole
  name: pod-ashiato-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-ashiato
  namespace: pod-ashiato
  labels:
    app: pod-ashiato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-ashiato
  template:
    metadata:
      labels:
        app: pod-ashiato
    spec:
      serviceAccountName: pod-ashiato
      containers:
      - name: pod-ashiato
        image: ghcr.io/takutakahashi/pod-ashiato:latest  # Use the published image
        args:
        - --interval=1m
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
